GET http://localhost:3002/subscribers/

###
GET http://localhost:3002/subscribers/

###
POST http://localhost:3002/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscriberToChannel": "Web Dev Simplified",
  "Path": "asdfadf"
}

###

PATCH http://localhost:3002/subscribers/

###

DELETE http://localhost:3002/subscribers/

###
